// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqbCvDccFlzsqHZfHwnPbfjmWlDsxp63A',
    appId: '1:5330226814:web:915f957e4cb9e80631522f',
    messagingSenderId: '5330226814',
    projectId: 'vittapet-cp5',
    authDomain: 'vittapet-cp5.firebaseapp.com',
    storageBucket: 'vittapet-cp5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOED-cx9tJl7vpz6w1OyMw05IdH4kH5mo',
    appId: '1:5330226814:android:a8d148716c3df6ac31522f',
    messagingSenderId: '5330226814',
    projectId: 'vittapet-cp5',
    storageBucket: 'vittapet-cp5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz10m4dxK-uNlFcoEEvVIu9pX1VvgI2Ao',
    appId: '1:5330226814:ios:7f7ba7affda9a8fc31522f',
    messagingSenderId: '5330226814',
    projectId: 'vittapet-cp5',
    storageBucket: 'vittapet-cp5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz10m4dxK-uNlFcoEEvVIu9pX1VvgI2Ao',
    appId: '1:5330226814:ios:7f7ba7affda9a8fc31522f',
    messagingSenderId: '5330226814',
    projectId: 'vittapet-cp5',
    storageBucket: 'vittapet-cp5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqbCvDccFlzsqHZfHwnPbfjmWlDsxp63A',
    appId: '1:5330226814:web:e557e4109c5f034731522f',
    messagingSenderId: '5330226814',
    projectId: 'vittapet-cp5',
    authDomain: 'vittapet-cp5.firebaseapp.com',
    storageBucket: 'vittapet-cp5.firebasestorage.app',
  );
}
